services:
    App\ChainCommandBundle\Command\SomeCommandCommand:
        tags:
          { name: 'console.command'}

    App\ChainCommandBundle\Command\AnotherCommandCommand:
        tags:
          { name: 'console.command'}

    App\ChainCommandBundle\Command\ThirdCommandCommand:
        tags:
          { name: 'console.command'}


